#!/usr/bin/env python3.2
"""
Script for listing all games in contrib.

games list
games info <game>

"""
from datetime import datetime, timedelta
from os import getenv, listdir, path
from random import randint
import argparse
import json
import logging
import re
import sys

CONTRIB_DIR = '/contrib/projects/'
GAMES_DIR = CONTRIB_DIR + 'games/'
MANUAL_ENTRY_DIR = GAMES_DIR + 'manual/' # TODO: The path is confusing.

MANUAL_ENTRY_POSTFIX = '.json'
GAME_JSON_FILE = '.games.json'

def main():
	args = set_and_parse_args()
	setup_logging(args.verbose)
	args.func(args)

def set_and_parse_args():
	parser = argparse.ArgumentParser(description='Student games information '
			'tool')
	parser.add_argument('-v', '--verbose', action='count', help='Show '
			'debugging information; -vv shows even more debugging information')
	subs = parser.add_subparsers(title='command', help='command help')

	list_parser = subs.add_parser('list', help='THIS IS HELPFUL')
	list_parser.set_defaults(func=print_games)

	info_parser = subs.add_parser('info', help='SO IS THIS')
	info_parser.set_defaults(func=show_game_info)

	return parser.parse_args()

def setup_logging(verbosity):
	"""Inits logging on the number of -v args received, given as verbosity."""
	if verbosity is None: level = logging.WARNING
	elif verbosity == 1: level = logging.INFO
	else: level = logging.DEBUG
	logging.basicConfig(level=level)

def print_games(options):
	"""Finds all games in contrib and displays them to the user."""
	for game in get_games_list():
		print(game)

def get_games_list():
	"""Returns a list of Game for all the games in contrib."""
	projects = set(listdir(CONTRIB_DIR))
	projects |= {re.sub('\.json$', '', f) for f in listdir(MANUAL_ENTRY_DIR)}
	games = []
	for proj_name in projects:
		game = load_game(proj_name)
		if isinstance(game, Game):
			logging.info('Successfully loaded "%s".' % proj_name)
			games.append(game)
	return games

def load_game(proj_name):
	"""Returns a Game if the given project is found, else returns None."""
	proj_path = CONTRIB_DIR + proj_name + '/' + GAME_JSON_FILE
	manual_entry_path = MANUAL_ENTRY_DIR + proj_name + MANUAL_ENTRY_POSTFIX

	json_paths = [proj_path, manual_entry_path]
	for path in json_paths:
		try:
			with open(path) as f:
				game_info = json.load(f)
		except IOError as e:
			# TODO: This is not true (ex: permission denied). Print e instead.
			logging.debug(path + ' does not exist.')
		except Exception as e: # TODO: Is there a more specific exception?
			logging.info('Invalid json for project "%s".' % proj_name)
		else:
			break
	else:
		logging.info('No valid .json file found for project "%s".' % proj_name)
		return None

	try:
		game = Game(proj_name, game_info)
	except Exception as e:
		logging.info('Unable to construct "%s".' % proj_name)
		logging.debug('Problems with construction: ' + str(e))
		return None
	return game

class Game:
	"""Represents a single contrib/ game."""
	def __init__(self, projname, game_info):
		log = ErrorLogger()

		self.projname = str(projname)
		self.name = log.getValue(game_info, 'name')
		self.desc = log.getValue(game_info, 'desc')
		self.url = log.getValue(game_info, 'name', False)

		self.loaded_json = game_info

		if not log.okay:
			raise Exception(log.log)

	def __str__(self):
		return self.loaded_json.__str__()

class ErrorLogger:
	log = ''
	okay = True

	def getValue(self, d, val, required=True):
		if val in d:
			return d[val]
		elif required:
			self.okay = False
			self.log += '\nMissing required "%s" attribute' % val
		else:
			return None

def show_game_info(options):
	pass

if __name__ == '__main__':
	main()
